CREATE TABLE goods (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    PRIORITY FLOAT
);

CREATE TABLE sales (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GOOD_ID INT,
    GOOD_COUNT INT,
    CREATE_DATE DATE NOT NULL,
    FOREIGN KEY (GOOD_ID) REFERENCES goods (ID)
);

CREATE TABLE warehouse1 (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GOOD_ID INT,
    GOOD_COUNT INT,
    FOREIGN KEY (GOOD_ID) REFERENCES goods (ID)
);

CREATE TABLE warehouse2 (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GOOD_ID INT,
    GOOD_COUNT INT,
    FOREIGN KEY (GOOD_ID) REFERENCES goods (ID)
);

CREATE TABLE USER_ROLE (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USER (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    USER_ROLE_ID INT,
    FOREIGN KEY (USER_ROLE_ID) REFERENCES users_roles (users_id)
);