CREATE TABLE goods (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    PRIORITY FLOAT
);

CREATE TABLE sales (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GOOD_ID INT,
    GOOD_COUNT INT,
    CREATE_DATE DATE NOT NULL,
    FOREIGN KEY (GOOD_ID) REFERENCES goods (ID)
);

CREATE TABLE warehouse1 (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GOOD_ID INT,
    GOOD_COUNT INT,
    FOREIGN KEY (GOOD_ID) REFERENCES goods (ID)
);

CREATE TABLE warehouse2 (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GOOD_ID INT,
    GOOD_COUNT INT,
    FOREIGN KEY (GOOD_ID) REFERENCES goods (ID)
);