CREATE TABLE goods(
    ID NUMERIC,
    NAME TEXT,
    PRIORITY FLOAT,
    PRIMARY KEY (ID)
);

CREATE TABLE sales(
    ID NUMERIC,
    GOOD_ID NUMERIC,
    GOOD_COUNT NUMERIC,
    CREATE_DATE TEXT,
    PRIMARY KEY (ID),
    FOREIGN KEY (GOOD_ID) REFERENCES goods(ID)
);

CREATE TABLE warehouse1(
    ID NUMERIC,
    GOOD_ID NUMERIC,
    GOOD_COUNT NUMERIC,
    PRIMARY KEY (ID),
    FOREIGN KEY (GOOD_ID) REFERENCES goods(ID)
);

CREATE TABLE warehouse2(
    ID NUMERIC,
    GOOD_ID NUMERIC,
    GOOD_COUNT NUMERIC,
    PRIMARY KEY (ID),
    FOREIGN KEY (GOOD_ID) REFERENCES goods(ID)
);